function mov = movies(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MOV = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  MOV = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  mov = movies("C:\Users\harip\Desktop\Recommendations\rec_sys_2\movies.dat", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jun-2021 10:01:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ":";

% Specify column names and types
opts.VariableNames = ["movieId", "movieName", "Var3", "Var4"];
opts.SelectedVariableNames = ["movieId", "movieName"];
opts.VariableTypes = ["double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["movieName", "Var3", "Var4"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["movieName", "Var3", "Var4"], "EmptyFieldRule", "auto");

% Import the data
mov = readtable(filename, opts);

end